### ISSUE TITLE
CreateFontW and CreateFontIndirectW

### ISSUE THREAD

**Issue by Cosetto** [Dir-A/RiaLibrary#1]
Can you support for those too?

**Comment by Dir-A** [comment]
https://github.com/Dir-A/RiaLibrary/commit/cb163e5f708ee69991c37f2e00a9acaca416f6ea

**Comment by Cosetto** [comment]
Thank you 👐

**Comment by Cosetto** [comment]
Ok, I'm sure what I'm doing wrong
```
	RxHook::HookCreateFontW(0x80, "Lune");
	RxHook::HookCreateFontIndirectW(0x80, "Lune");
```
![image](https://github.com/Dir-A/RiaLibrary/assets/81801486/811dfcf5-e3e8-42ab-9af5-13897fac39d7)

**Comment by Dir-A** [comment]
Its parameters are wide bytes
so you need to prefix the string with L


```
RxHook::HookCreateFontW(0x80, L"Lune");
```

**Comment by Cosetto** [comment]
Thanks again bro
